extends SceneTree
## Headless syntax check for editor addon scripts. Run from project root:
##   godot --headless --path . --script res://tools/validate_scripts.gd

const _PATHS := [
	"res://addons/uf_map_editor/plugin.gd",
	"res://addons/uf_map_editor/dock.gd",
	"res://core/events.gd",
	"res://autoload/event_bus.gd",
	"res://modules/attributes/attributes.gd",
	"res://modules/attributes/attribute_set.gd",
	"res://modules/appearance/appearance.gd",
	"res://modules/appearance/inspection_layout_def.gd",
	"res://modules/npc/npc.gd",
	"res://modules/npc/npc_archetype.gd",
	"res://modules/npc/npc_instance_data.gd",
	"res://modules/appearance/npc_appearance_controller.gd",
	"res://modules/appearance/cutout_orientation.gd",
	"res://modules/appearance/part_visual_def.gd",
	"res://modules/modifier/modifier_def.gd",
	"res://modules/modifier/modifier.gd",
	"res://modules/faction/faction_def.gd",
	"res://modules/faction/faction.gd",
	"res://modules/equipment/equipment_visual_def.gd",
	"res://modules/equipment/equipment_slot_map.gd",
	"res://modules/equipment/equipment_state.gd",
	"res://modules/equipment/equipment.gd",
	"res://modules/items/items.gd",
	"res://modules/items/item_def.gd",
	"res://modules/items/item_instance.gd",
	"res://modules/items/item_state_tier_def.gd",
	"res://modules/items/item_quality_tier_def.gd",
	"res://modules/items/item_category_def.gd",
	"res://modules/items/item_tag_def.gd",
	"res://modules/items/item_sprite_ref.gd",
	"res://modules/items/weapon_item_data.gd",
	"res://modules/items/food_item_data.gd",
	"res://modules/items/valuable_item_data.gd",
	"res://modules/items/armor_item_data.gd",
	"res://modules/world/world.gd",
	"res://modules/gui/gui.gd",
	"res://modules/gui/uf_panel.gd",
	"res://modules/gui/uf_panel_ingame.gd",
	"res://modules/gui/uf_info_panel.gd",
	"res://modules/gui/uf_dialog_panel.gd",
	"res://modules/gui/uf_tabbed_panel.gd",
	"res://modules/gui/uf_inspection_panel.gd",
	"res://modules/gui/uf_panel_ingame_loot.gd",
	"res://modules/gui/uf_panel_ingame_status.gd",
	"res://modules/gui/widgets/uf_label.gd",
	"res://modules/gui/widgets/uf_button.gd",
	"res://modules/gui/widgets/uf_list.gd",
	"res://modules/gui/widgets/uf_grid_container.gd",
	"res://modules/gui/widgets/uf_layout_region.gd",
	"res://modules/gui/widgets/uf_equipment_slot.gd",
	"res://modules/gui/widgets/uf_item_slot.gd",
	"res://modules/gui/widgets/uf_tab.gd",
	"res://addons/uf_gui_tools/plugin.gd",
	"res://addons/uf_gui_tools/dock.gd",
	"res://addons/uf_gui_tools/palette_item.gd",
	"res://addons/uf_gui_tools/widget_palette.gd",
	"res://addons/uf_npc_editor/plugin.gd",
	"res://addons/uf_npc_editor/workspace.gd",
	"res://addons/uf_npc_editor/editor_i18n.gd",
	"res://addons/uf_npc_editor/compatible_item.gd",
	"res://addons/uf_item_editor/plugin.gd",
	"res://addons/uf_item_editor/workspace.gd",
	"res://addons/uf_item_editor/item_list_row.gd",
	"res://addons/uf_item_editor/item_preview_summary.gd",
	"res://addons/uf_item_editor/editor_i18n.gd",
	"res://addons/uf_item_editor/editor_block.gd",
	"res://addons/uf_item_editor/tag_chip.gd",
	"res://addons/uf_item_editor/tag_flow.gd",
	"res://addons/uf_item_editor/tag_assign_zone.gd",
	"res://scenes/game/game_session.gd",
	"res://scenes/game/game_bootstrap.gd",
	"res://scenes/game/game_hud.gd",
	"res://scenes/game/player_inventory_bridge.gd",
	"res://modules/gui/uf_panel_ingame_inventory.gd",
	"res://scenes/game/player_controller.gd",
]

func _initialize() -> void:
	var failed := false
	for path in _PATHS:
		var script: Variant = load(path)
		if script == null:
			push_error("FAIL load: %s" % path)
			failed = true
		else:
			print("OK: %s" % path)
	quit(1 if failed else 0)
